clc;
clear;

% 实验名称用于定位最终结果
experiment_name = '墨西哥湾_20260611';

% 预览行数用于控制台检查
preview_row_count = 5;

% 读取项目路径和中间结果路径
script_path = mfilename('fullpath');
project_root = fileparts(fileparts(script_path));
output_dir = fullfile(project_root, ['结果_', experiment_name]);
intermediate_dir = fullfile(output_dir, '01_中间数据');
table_dir = fullfile(output_dir, '03_结果表格');
sar_info_path = fullfile(intermediate_dir, 'SAR_info_25x25.mat');
excel_path = fullfile(table_dir, '海面风速反演结果.xlsx');

% 创建表格输出目录
if ~exist(table_dir, 'dir')
    mkdir(table_dir);
end

% 载入最终结果
if ~exist(sar_info_path, 'file')
    error('未找到最终中间结果，请先运行前四步脚本。');
end
load(sar_info_path, ...
    'small_arealon', 'small_arealat', 'small_areainc', 'small_areasig', 'sigma_valid_ratio', ...
    'small_wind_speed', 'small_wind_dir', 'sar_wind_speed', 'minimum_residual');

% 载入样本筛选结果
validation_path = fullfile(intermediate_dir, '验证指标.mat');
if exist(validation_path, 'file')
    load(validation_path, 'wind_error', 'abs_wind_error', 'model_quality_mask', 'strict_model_quality_mask', 'lower_bound_mask');
else
    wind_error = sar_wind_speed - small_wind_speed;
    abs_wind_error = abs(wind_error);
    model_quality_mask = isfinite(wind_error);
    strict_model_quality_mask = model_quality_mask;
    lower_bound_mask = false(size(wind_error));
end

% 整理 25x25 网格结果表
result_table = table( ...
    small_arealon(:), ...
    small_arealat(:), ...
    small_areainc(:), ...
    small_areasig(:), ...
    sigma_valid_ratio(:), ...
    small_wind_speed(:), ...
    small_wind_dir(:), ...
    sar_wind_speed(:), ...
    minimum_residual(:), ...
    wind_error(:), ...
    abs_wind_error(:), ...
    model_quality_mask(:), ...
    strict_model_quality_mask(:), ...
    lower_bound_mask(:), ...
    'VariableNames', { ...
        'Longitude', ...
        'Latitude', ...
        'Incident_Angle', ...
        'Sigma0_VV', ...
        'Sigma0_Valid_Ratio', ...
        'ERA5_Wind_Speed', ...
        'ERA5_Wind_Direction', ...
        'SAR_Wind_Speed', ...
        'CMOD_Minimum_Residual', ...
        'Wind_Error', ...
        'Abs_Wind_Error', ...
        'Is_CMOD_Residual_Filtered', ...
        'Is_Strict_CMOD_Residual_Filtered', ...
        'Is_Lower_Bound_Result'});

% 导出 Excel 表格
writetable(result_table, excel_path);

% 打印前几行检查结果
fprintf('第五步完成：已导出 25x25 海面风速结果表。\n');
fprintf('Excel 文件：%s\n', excel_path);
fprintf('前 %d 行数据预览：\n', preview_row_count);
disp(result_table(1:preview_row_count, :));
